src/smi_unb/buildings/urls.py
from django.conf.urls import url
from . import views

app_name = 'buildings'
urlpatterns = [
    url(
        r'^novo&campus=(?P<campus_string>[\w\-]+)/$',
        views.new_building,
        name="new_building"
    ),
    url(
        r'^(?P<building_id>[0-9]+)/$',
        views.index,
        name="index"
    ),
    url(
        r'^(?P<building_id>[0-9]+)/info/$',
        views.building_info,
        name="building_info"
    ),
    url(
        r'^(?P<building_id>[0-9]+)/transdutores_defeituosos/$',
        views.building_broken_transductors,
        name="building_broken_transductors"
    ),
    url(
        r'^(?P<building_id>[0-9]+)/edit\&campus=(?P<campus_string>[\w\-]+)/$',
        views.edit_building,
        name="edit_building"
    ),
    url(
        r'^(?P<building_id>[0-9]+)/enable/$',
        views.enable_building,
        name="enable_building"
    ),
    url(
        r'^(?P<building_id>[0-9]+)/disable/$',
        views.disable_building,
        name="disable_building"
    ),
    url(
        r'^(?P<building_id>[0-9]+)/transdutores_desativados/$',
        views.inactive_transductors,
        name="inactive_transductors"
    ),
]

src/smi_unb/campuses/urls.py
from django.conf.urls import url

from . import views

app_name = 'campuses'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(
        r'^(?P<campus_string>[\w\-]+)/$',
        views.campus_index,
        name="campus_index"
    ),
    url(
        r'^(?P<campus_string>[\w\-]+)/info/$',
        views.campus_info,
        name="campus_info"
    ),
    url(
        r'^(?P<campus_string>[\w\-]+)/desativados/$',
        views.inactive_buildings,
        name="inactive_buildings"
    ),
]

src/smi_unb/transductor/urls.py
from django.conf.urls import url

from . import views

app_name = 'transductor'

urlpatterns = [
    url(r'^novo\&predio=(?P<building_id>[0-9]+)$', views.new, name='new'),
    url(r'^(?P<transductor_id>[0-9]+)/info$', views.info, name='info'),
    url(r'^(?P<transductor_id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(
        r'^(?P<transductor_id>[0-9]+)/enable/$',
        views.enable,
        name='enable'),
    url(
        r'^(?P<transductor_id>[0-9]+)/disable/$',
        views.disable,
        name='disable'),
]

src/smi_unb/urls.py
import smi_unb.api.views as api_views

from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers

from smi_unb import views

router = routers.DefaultRouter()
router.register(r'building', api_views.BuildingViewSet)
router.register(r'energy_measurement', api_views.EnergyMeasurementsViewSet)
router.register(r'energy_transductor', api_views.EnergyTransductorViewSet)

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^campi/', include('smi_unb.campuses.urls', namespace="campuses")),
    url(r'^painel_controle/$', views.dashboard, name="dashboard"),
    url(r'^reports/', include('smi_unb.report.urls', namespace="report")),
    url(r'^usuarios/', include('smi_unb.users.urls', namespace="users")),
    url(
        r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework')),
    url(
        r'^autenticacao/',
        include('smi_unb.authentication.urls', namespace="authentication")),
    url(
        r'^minha_conta/',
        include('smi_unb.my_account.urls', namespace="my_account")),
    url(
        r'^predios/',
        include('smi_unb.buildings.urls', namespace="buildings")),
    url(
        r'^recuperar_senha/',
        include('smi_unb.retrieve_password.urls', namespace="retrieve")),
    url(
        r'^transdutor/',
        include('smi_unb.transductor.urls', namespace="transductor")),
]

src/smi_unb/buildings/models.py
from django.core.validators import RegexValidator
from django.db import models

from smi_unb.campuses.models import Campus


class BuildingManager(models.Manager):
    def get_all_active_buildings(self):
        return self.get_queryset().filter(active=True)

    def get_all_inactive_buildings(self):
        return self.get_queryset().filter(active=False)


class Building(models.Model):
    campus = models.ForeignKey(Campus, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=50)
    acronym = models.CharField(max_length=10, blank=True)
    description = models.CharField(max_length=150, blank=True)
    phone = models.CharField(max_length=16, blank=True)
    website_address = models.CharField(max_length=100, blank=True)
    server_ip_address = models.CharField(
        max_length=15,
        unique=True,
        validators=[
            RegexValidator(
                regex='^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$',
                message='Incorrect IP address format',
                code='invalid_ip_address'
            ),
        ]
    )
    active = models.BooleanField(default=True)
    synchronized = models.BooleanField(default=False)
    objects = BuildingManager()

    def __str__(self):
        return self.name

    def get_all_working_transductors(self):
        return self.transductor_set.filter(broken=False, active=True)

    def get_all_broken_transductors(self):
        return self.transductor_set.filter(broken=True, active=True)

    def get_all_active_transductors(self):
        return self.transductor_set.filter(active=True)

    def get_all_inactive_transductors(self):
        return self.transductor_set.filter(active=False)

    def set_building_active(self):
        self.active = True

    def set_building_inactive(self):
        self.active = False

    def update_transductors_sent(self, id_transductors_to_update):
        transductors_updated = []

        for id_transductor in id_transductors_to_update:
            transductor = self.transductor_set.get(id=id_transductor)
            transductor.update_last_measurement_sent()

            transductors_updated.append(transductor)

        return transductors_updated

    def api_view_set(self):
        return 'building'

src/smi_unb/buildings/forms.py
import requests

from django import forms
from django.utils.translation import ugettext as _

from .models import Building


class BuildingForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        campus = kwargs.pop('campus')
        super(BuildingForm, self).__init__(*args, **kwargs)
        self.fields['campus'].label = "Campus"
        self.fields['campus'].widget = forms.Select(
            attrs={
                'class': 'selectpicker form-control'
            }
        )
        self.fields['campus'].empty_label = None
        self.fields['campus'].queryset = self.fields['campus'] \
                                             .queryset.filter(id=campus.id)

    class Meta:
        model = Building
        fields = (
            'campus', 'name', 'acronym', 'server_ip_address', 'description',
            'phone', 'website_address'
        )

    name = forms.CharField(
        label="Nome",
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'name': 'name',
                'size': 50,
                'type': 'text'
            }
        )
    )

    acronym = forms.CharField(
        label="Sigla",
        max_length=10,
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'name': 'acronym',
                'size': 10,
                'type': 'text'
            }
        )
    )

    server_ip_address = forms.CharField(
        label="Endereço de IP do Servidor",
        max_length=15,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'name': 'server_ip_address',
                'size': 10,
                'type': 'text'
            }
        )
    )

    description = forms.CharField(
        label="Descrição",
        max_length=150,
        required=False,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'name': 'description',
                'size': 150,
                'type': 'text'
            }
        )
    )

    phone = forms.CharField(
        label="Telefone",
        max_length=16,
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'name': 'phone',
                'size': 16,
                'type': 'text'
            }
        )
    )

    website_address = forms.CharField(
        label="URL do Site",
        max_length=100,
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'name': 'website_address',
                'size': 100,
                'type': 'text'
            }
        )
    )

    def is_valid(self):
        valid = super(BuildingForm, self).is_valid()

        if not valid:
            return valid

        url = 'http://' + self.instance.server_ip_address
        try:
            request = requests.get(url, timeout=3)
        except BaseException:
            self.add_error(
                None,
                _('Não foi possível comunicar com o servidor do Edifício. ' +
                  'Verifique o endereço de IP informado.')
            )
            return False

        if request.status_code != 200:
            self.add_error(
                None,
                _('Não foi possível comunicar com o servidor do Edifício. ' +
                  'Verifique o endereço de IP informado.')
            )
            return False

        return True


class EnableBuildingForm(forms.ModelForm):
    class Meta:
        model = Building
        fields = []

    def is_valid(self):
        valid = super(EnableBuildingForm, self).is_valid()

        if not valid:
            return valid

        if self.instance.active:
            return False

        url = 'http://' + self.instance.server_ip_address
        try:
            request = requests.get(url, timeout=3)
        except BaseException:
            self.add_error(
                None,
                _('Não foi possível comunicar com o servidor do Edifício. ' +
                  'Verifique o endereço de IP informado.')
            )
            return False

        if request.status_code != 200:
            self.add_error(
                None,
                _('Não foi possível comunicar com o servidor do Edifício. ' +
                  'Verifique o endereço de IP informado.')
            )
            return False

        return True


class DisableBuildingForm(forms.ModelForm):
    class Meta:
        model = Building
        fields = []

    def is_valid(self):
        valid = super(DisableBuildingForm, self).is_valid()

        if not valid:
            return valid

        if not self.instance.active:
            return False

        return True

src/smi_unb/buildings/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.utils.translation import ugettext as _

from smi_unb.api.synchronization import SyncManager
from smi_unb.campuses.models import Campus
from .forms import BuildingForm, EnableBuildingForm, DisableBuildingForm
from .models import Building


@login_required
def index(request, building_id):
    building = get_object_or_404(Building, pk=building_id)

    transductors_list = building.get_all_active_transductors()
    inactive_transductors = bool(building.get_all_inactive_transductors())

    return render(
        request,
        'buildings/building_index.html',
        {
            'campus': building.campus,
            'building': building,
            'transductors_list': transductors_list,
            'inactive_transductors': inactive_transductors
        }
    )


@login_required
@user_passes_test(
    lambda user: user.has_perm("users.manager_buildings"),
    login_url='/painel_controle/',
    redirect_field_name=None)
def new_building(request, campus_string):
    campus = get_object_or_404(Campus, url_param=campus_string)

    if request.POST:
        form = BuildingForm(request.POST, campus=campus)

        if form.is_valid():
            building = form.save()

            building.synchronized = SyncManager.sync_building(
                building, new=True)

            building.save()

            return HttpResponseRedirect(
                reverse(
                    'campuses:campus_index',
                    kwargs={'campus_string': campus.url_param}
                )
            )
    else:
        form = BuildingForm(
            campus=campus
        )

    return render(
        request,
        'buildings/new_building.html',
        {'campus': campus, 'form': form}
    )


@login_required
@user_passes_test(
    lambda user: user.has_perm("users.manager_buildings"),
    login_url='/painel_controle/',
    redirect_field_name=None)
def edit_building(request, building_id, campus_string):
    building = get_object_or_404(Building, pk=building_id)

    if not building.campus.url_param == campus_string:
        return render(request, '404.html')

    if request.POST:
        form = BuildingForm(
            request.POST,
            instance=building,
            campus=building.campus
        )

        if form.is_valid():
            if form.has_changed():
                building = form.save(commit=False)

                building.synchronized = SyncManager.sync_building(
                    building)

                building.save()

                return HttpResponseRedirect(
                    reverse(
                        'buildings:building_info',
                        kwargs={
                            'building_id': building.id
                        }
                    )
                )
            else:
                form.add_error(None, _("Nenhuma Mudança Encontrada."))
    else:
        form = BuildingForm(instance=building, campus=building.campus)

    return render(
        request,
        'buildings/edit_building.html',
        {'campus': building.campus, 'building': building, 'form': form}
    )


@login_required
@user_passes_test(
    lambda user: user.has_perm("users.manager_buildings"),
    login_url='/painel_controle/',
    redirect_field_name=None)
def enable_building(request, building_id):
    building = get_object_or_404(Building, pk=building_id)

    if request.POST:
        form = EnableBuildingForm(request.POST, instance=building)

        if form.is_valid():
            building = form.save(commit=False)
            building.set_building_active()
            building.synchronized = SyncManager.sync_building(
                building)
            building.save()

            next_page = request.POST.get('next')

            if next_page:
                return HttpResponseRedirect(next_page)

    return HttpResponseRedirect(
        reverse(
            'buildings:building_info',
            kwargs={'building_id': building.id}
        )
    )


@login_required
@user_passes_test(
    lambda user: user.has_perm("users.manager_buildings"),
    login_url='/painel_controle/',
    redirect_field_name=None)
def disable_building(request, building_id):
    building = get_object_or_404(Building, pk=building_id)

    if request.POST:
        form = DisableBuildingForm(request.POST, instance=building)

        if form.is_valid():
            building = form.save(commit=False)
            building.set_building_inactive()
            building.synchronized = SyncManager.sync_building(
                building)
            building.save()

    return HttpResponseRedirect(
        reverse(
            'buildings:building_info',
            kwargs={'building_id': building.id}
        )
    )


@login_required
def building_info(request, building_id):
    building = get_object_or_404(Building, pk=building_id)

    return render(
        request,
        'buildings/building_info.html',
        {
            'campus': building.campus,
            'building': building
        }
    )


@login_required
def building_broken_transductors(request, building_id):
    building = get_object_or_404(Building, pk=building_id)

    broken_transductors = building.get_all_broken_transductors()

    return render(
        request,
        'buildings/building_broken_transductors.html',
        {
            'campus': building.campus,
            'building': building,
            'broken_transductors': broken_transductors
        }
    )


@login_required
@user_passes_test(
    lambda user: user.has_perm("users.manager_transductors"),
    login_url='/painel_controle/',
    redirect_field_name=None)
def inactive_transductors(request, building_id):
    building = get_object_or_404(Building, pk=building_id)
    inactive_transductors = building.get_all_inactive_transductors()

    return render(
        request,
        'buildings/inactive_transductors.html',
        {
            'campus': building.campus,
            'building': building,
            'inactive_transductors': inactive_transductors
        }
    )

src/smi_unb/buildings/templates/buildings/building_broken_transductors.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
  {{building.name}} - {% trans "Transdutores Defeituosos" %}
{% endblock %}

{% block header %}
<div id="head" class="secondary" style=></div>
{% endblock %}

{% block body %}
<div class="container">

  <ol class="breadcrumb">
    <li><a href="{% url 'index' %}">{% trans "Início" %}</a></li>
    <li><a href="{% url 'dashboard' %}">{% trans "Painel de Controle" %}</a></li>
    <li><a href="{% url 'campuses:index' %}">{% trans "Câmpus" %}</a></li>
    <li><a href="{% url 'campuses:campus_index' campus.url_param %}">{{campus.acronym}}</a></li>
    <li class="active">{{building.name}} - {% trans "Transdutores Defeituosos" %}</li>
  </ol>

  <div class="row">
    <article class="col-xs-12 maincontent">

      <header class="page-header">
        <h1 class="page-title">{{building.name}} - {% trans "Transdutores com Defeito" %}</h1>
      </header>

      <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
        <div class="panel panel-default">
          <div class="panel-body">
            <h3 class="thin text-center">{% trans "Lista de Transdutores" %}</h3>
            <hr>

            {% if broken_transductors %}
              <table id="centered_table" class="table table-bordered">
                <thead>
                  <tr>
                    <th>{% trans "Nome" %}</th>
                    <th>{% trans "Modelo" %}</th>
                    <th>{% trans "Funcionando" %}</th>
                  </tr>
                </thead>

                <tbody>
                  {% for transductor in broken_transductors %}
                    <tr>
                      <td><a href="{% url 'transductor:info' transductor.id %}">{{transductor.name}}</a></td>
                      <td>{{transductor.model}}</td>

                      {% if transductor.broken%}
                        <td><span id="broken" class="glyphicon glyphicon-remove"></td>
                      {% else %}
                        <td><span class="glyphicon glyphicon-ok"></td>
                      {% endif %}
                    </tr>
                  {% endfor %}
                </tbody>
              </table>

            {% else %}
              <div class="container">
                <div class="starter-template">
                  <h2>{% trans "Nenhum Transdutor Registrado" %}</h2>
                </div>
              </div>
            {% endif %}
          </div> <!-- end div panel- -->
        </div>
      </div>
    </article>
  </div>
</div>
{% endblock %}

src/smi_unb/buildings/templates/buildings/building_index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
  {{building.name}}
{% endblock %}

{% block header %}
<div id="head" class="secondary" style=></div>
{% endblock %}

{% block body %}
<div class="container">

  <ol class="breadcrumb">
    <li><a href="{% url 'index' %}">{% trans "Início" %}</a></li>
    <li><a href="{% url 'dashboard' %}">{% trans "Painel de Controle" %}</a></li>
    <li><a href="{% url 'campuses:index' %}">{% trans "Câmpus" %}</a></li>
    <li><a href="{% url 'campuses:campus_index' campus.url_param %}">{{campus.acronym}}</a></li>
    <li class="active">{{building.name}}</li>
  </ol>

  <div class="row">
    <article class="col-xs-12 maincontent">

      <header class="page-header">
        <h1 class="page-title">{{building.name}}</h1>
      </header>

      <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
        <div class="text-center">
          <b><a href="{% url 'buildings:building_info' building.id %}" class="btn btn-primary">{% trans "Informações do Edifício" %}</a></b>

          {% if perms.users.manager_transductors %}
            <b><a href="{% url 'transductor:new' building.id %}" class="btn btn-success">{% trans "Cadastrar Transdutor" %}</a></b>

            {% if inactive_transductors %}
              <b><a href="{% url 'buildings:inactive_transductors' building.id %}" class="btn btn-info">{% trans "Transdutores Desativados" %}</a></b>
            {% endif %}
          {% endif %}
        </div>
        <hr>

        <div class="panel panel-default">
          <div class="panel-body">
            <h3 class="thin text-center">{% trans "Lista de Transdutores" %}</h3>
            <hr>

            {% if transductors_list %}
              <table id="centered_table" class="table table-bordered">
                <thead>
                  <tr>
                    <th>{% trans "Nome" %}</th>
                    <th>{% trans "Modelo" %}</th>
                    <th>{% trans "Funcionando" %}</th>
                  </tr>
                </thead>

                <tbody>
                  {% for transductor in transductors_list %}
                    <tr>
                      <td><a href="{% url 'transductor:info' transductor.id %}">{{transductor.name}}</a></td>
                      <td>{{transductor.model}}</td>

                      {% if transductor.broken%}
                        <td><span id="broken" class="glyphicon glyphicon-remove"></td>
                      {% else %}
                        <td><span class="glyphicon glyphicon-ok"></td>
                      {% endif %}
                    </tr>
                  {% endfor %}
                </tbody>
              </table>

            {% else %}
              <div class="container">
                <div class="starter-template">
                  <h2>{% trans "Nenhum Transdutor Registrado" %}</h2>
                </div>
              </div>
            {% endif %}
          </div> <!-- end div panel- -->
        </div>
      </div>
    </article>
  </div>
</div>
{% endblock %}

src/smi_unb/buildings/templates/buildings/building_info.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
  {{building.name}} - {% trans "Informações" %}
{% endblock %}

{% block header %}
<div id="head" class="secondary" style=></div>
{% endblock %}

{% block body %}
<div class="container">

  <ol class="breadcrumb">
    <li><a href="{% url 'index' %}">{% trans "Início" %}</a></li>
    <li><a href="{% url 'dashboard' %}">{% trans "Painel de Controle" %}</a></li>
    <li><a href="{% url 'campuses:index' %}">{% trans "Câmpus" %}</a></li>
    <li><a href="{% url 'campuses:campus_index' campus.url_param %}">{{campus.acronym}}</a></li>
    <li><a href="{% url 'buildings:index' building.id %}">{{building.name}}</a></li>
    <li class="active">{% trans "Informações do Edifício" %}</li>
  </ol>

  <div class="row">
    <article class="col-xs-12 maincontent">

      <header class="page-header">
        <h1 class="page-title">{{building.name}} - {% trans "Informações" %}</h1>
      </header>

      <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
        {% if perms.users.manager_buildings %}
          <div class="text-center">
            <b><a href="{% url 'buildings:edit_building' building.id campus.url_param %}" class="btn btn-warning">{% trans "Editar Informações" %}</a></b>

            {% if building.active %}
            <form class="enable_disable_buttons" action="{% url 'buildings:disable_building' building_id=building.id %}" method="post">
              {% csrf_token %}
              <button class="btn btn-danger" onclick="return confirm('Deseja realmente desativar?')">{% trans "Desativar Edifício" %}</button>
            </form>

            {% else %}
            <form class="enable_disable_buttons" action="{% url 'buildings:enable_building' building_id=building.id %}" method="post">
              {% csrf_token %}
              <button class="btn btn-success" onclick="return confirm('Deseja realmente ativar?')">{% trans "Ativar Edifício" %}</button>
            </form>
            {% endif %}
          </div>
        <hr>
        {% endif %}

        <div class="panel panel-default">
          <div class="panel-body">
            <h3 class="thin text-center">{% trans "Informações" %}</h3>
            <hr>

            <div class="top-margin">
              <label>{% trans "Campus" %}:</label>
              <p>{{building.campus.name}}</p>
            </div>

            <div class="top-margin">
              <label>{% trans "Nome" %}:</label>
              <p>{{building.name}}</p>
            </div>

            <div class="top-margin">
              <label>{% trans "Sigla" %}:</label>
              <p>{{building.acronym}}</p>
            </div>

            {% if perms.users.manager_buildings %}
              <div class="top-margin">
                <label>{% trans "Endereço de IP do Servidor" %}:</label>
                <p>{{building.server_ip_address}}</p>
              </div>
            {% endif %}

            <div class="top-margin">
              <label>{% trans "Descrição" %}:</label>
              <p>{{building.description}}</p>
            </div>

            <div class="top-margin">
              <label>{% trans "Telefone" %}:</label>
              <p>{{building.phone}}</p>
            </div>

            <div class="top-margin">
              <label>{% trans "URL do Site" %}:</label>
              {% if building.website_address %}
                <p><a href="{{building.website_address}}">{{building.name}}</a></p>
              {% endif %}
            </div>
          </div> <!-- end div panel- -->
        </div>
      </div>
    </article>
  </div>
</div>
{% endblock %}

src/smi_unb/buildings/templates/buildings/inactive_transductors.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
  {{campus.acronym}} - {% trans "Edifícios Desativados" %}
{% endblock %}

{% block extrastyle %}
  <link rel="stylesheet" type="text/css" href="{% static 'campuses/css/campuses.css' %}" />
{% endblock %}

{% block header %}
<div id="head" class="secondary" style=></div>
{% endblock %}

{% block body %}
<div class="container">

  <ol class="breadcrumb">
    <li><a href="{% url 'index' %}">{% trans "Início" %}</a></li>
    <li><a href="{% url 'dashboard' %}">{% trans "Painel de Controle" %}</a></li>
    <li><a href="{% url 'campuses:index' %}">{% trans "Câmpus" %}</a></li>
    <li><a href="{% url 'campuses:campus_index' campus.url_param %}">{{campus.acronym}}</a></li>
    <li><a href="{% url 'buildings:index' building.id %}">{{building.name}}</a></li>
    <li class="active">{% trans "Transdutores Desativados" %}</li>
  </ol>

  <div class="row">
    <article class="col-xs-12 maincontent">

      <header class="page-header">
        <h1 class="page-title">{{campus.name}} - {% trans "Transdutores Desativados" %}</h1>
      </header>

      <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
        <div class="panel panel-default">
          <div class="panel-body">
            <h3 class="thin text-center">{% trans "Lista de Transdutores" %}</h3>
            <hr>

            {% if inactive_transductors %}
              <table id="centered_table" class="table table-bordered">
                <thead>
                  <tr>
                    <th>{% trans "Nome" %}</th>
                    <th>{% trans "Modelo" %}</th>
                    <th>{% trans "Funcionando" %}</th>
                    <th>{% trans "Opções" %}</th>
                  </tr>
                </thead>

                <tbody>
                  {% for transductor in inactive_transductors %}
                    <tr>
                      <td><a href="{% url 'transductor:info' transductor.id %}">{{transductor.name}}</a></td>
                      <td>{{transductor.model}}</td>

                      {% if transductor.broken%}
                        <td><span id="broken" class="glyphicon glyphicon-remove"></td>
                      {% else %}
                        <td><span class="glyphicon glyphicon-ok"></td>
                      {% endif %}

                      <td>
                        <form class="enable_disable_buttons" action="{% url 'transductor:enable' transductor.id %}" method="post">
                          {% csrf_token %}
                          <button class="btn btn-success" onclick="return confirm('Deseja realmente habilitar o transdutor?')">{% trans "Ativar Transdutor" %}</button>
                          <input type="hidden" name="next" value="{% url 'buildings:index' building.id %}">
                        </form>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>

            {% else %}
              <div class="container">
                <div class="starter-template">
                  <h2>{% trans "Nenhum Transdutor Desativado" %}</h2>
                </div>
              </div>
            {% endif %}
          </div> <!-- end div panel- -->
        </div>
      </div>
    </article>
  </div>
</div>
{% endblock %}