src/smi_unb/campuses/urls.py
from django.conf.urls import url

from . import views

app_name = 'campuses'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(
        r'^(?P<campus_string>[\w\-]+)/$',
        views.campus_index,
        name="campus_index"
    ),
    url(
        r'^(?P<campus_string>[\w\-]+)/info/$',
        views.campus_info,
        name="campus_info"
    ),
    url(
        r'^(?P<campus_string>[\w\-]+)/desativados/$',
        views.inactive_buildings,
        name="inactive_buildings"
    ),
]

src/smi_unb/transductor/urls.py
from django.conf.urls import url

from . import views

app_name = 'transductor'

urlpatterns = [
    url(r'^novo\&predio=(?P<building_id>[0-9]+)$', views.new, name='new'),
    url(r'^(?P<transductor_id>[0-9]+)/info$', views.info, name='info'),
    url(r'^(?P<transductor_id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(
        r'^(?P<transductor_id>[0-9]+)/enable/$',
        views.enable,
        name='enable'),
    url(
        r'^(?P<transductor_id>[0-9]+)/disable/$',
        views.disable,
        name='disable'),
]

src/smi_unb/urls.py
import smi_unb.api.views as api_views

from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers

from smi_unb import views

router = routers.DefaultRouter()
router.register(r'building', api_views.BuildingViewSet)
router.register(r'energy_measurement', api_views.EnergyMeasurementsViewSet)
router.register(r'energy_transductor', api_views.EnergyTransductorViewSet)

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^campi/', include('smi_unb.campuses.urls', namespace="campuses")),
    url(r'^painel_controle/$', views.dashboard, name="dashboard"),
    url(r'^reports/', include('smi_unb.report.urls', namespace="report")),
    url(r'^usuarios/', include('smi_unb.users.urls', namespace="users")),
    url(
        r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework')),
    url(
        r'^autenticacao/',
        include('smi_unb.authentication.urls', namespace="authentication")),
    url(
        r'^minha_conta/',
        include('smi_unb.my_account.urls', namespace="my_account")),
    url(
        r'^predios/',
        include('smi_unb.buildings.urls', namespace="buildings")),
    url(
        r'^recuperar_senha/',
        include('smi_unb.retrieve_password.urls', namespace="retrieve")),
    url(
        r'^transdutor/',
        include('smi_unb.transductor.urls', namespace="transductor")),
]

src/smi_unb/transductor/forms.py
import requests

from django import forms
from django.utils import timezone
from django.utils.translation import ugettext as _

from .models import EnergyTransductor, TransductorModel


class EnergyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        building = kwargs.pop('building')
        super(EnergyForm, self).__init__(*args, **kwargs)

        self.fields['building'].label = "Edifício"
        self.fields['building'].widget = forms.Select(
            attrs={
                'class': 'selectpicker form-control'
            }
        )
        self.fields['building'].empty_label = None
        self.fields['building'].queryset = self.fields['building'] \
                                               .queryset \
                                               .filter(id=building.id)

    class Meta:
        model = EnergyTransductor
        fields = (
            'building', 'model', 'ip_address', 'name', 'serie_number',
            'local_description', 'comments', 'calibration_date'
        )

    model = forms.ModelChoiceField(
        label="Modelo",
        queryset=TransductorModel.objects.all(),
        required=True,
        initial=0,
        widget=forms.Select(
            attrs={
                'class': 'selectpicker form-control',
                'data-live-search': 'true'
            }
        )
    )

    ip_address = forms.CharField(
        label="Número de IP",
        max_length=15,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'name': 'ip_address',
                'size': 15,
                'type': 'text'
            }
        )
    )

    name = forms.CharField(
        label="Nome",
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'name': 'name',
                'size': 50,
                'type': 'text'
            }
        )
    )

    serie_number = forms.IntegerField(
        label="Número de Serie",
        required=False,
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
                'name': 'serie_number',
                'min': '0', 'max':
                '999999'
            }
        )
    )

    local_description = forms.CharField(
        label="Descrição do Local Instalado",
        max_length=150,
        required=False,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'name': 'description',
                'size': 150,
                'type': 'text'
            }
        )
    )

    comments = forms.CharField(
        label="Comentários",
        max_length=150,
        required=False,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'name': 'description',
                'size': 150,
                'type': 'text'
            }
        )
    )

    calibration_date = forms.DateTimeField(
        input_formats=['%d/%m/%Y %H:%M'],
        label="Data Última Calibração",
        widget=forms.DateTimeInput(
            attrs={
                'class': 'form-control',
                'type': 'text',
                'id': 'id_calibration_date'
            }
        ),
        required=False
    )

    def is_valid(self):
        valid = super(EnergyForm, self).is_valid()

        if not valid:
            return valid

        calibration_date = self.cleaned_data['calibration_date']

        if calibration_date:
            now = timezone.now()

            if calibration_date > now:
                self.add_error(
                    'calibration_date',
                    _('Data de calibração não ' +
                      'pode ser depois do horário atual.')
                )

                return False

        url = 'http://' + self.instance.building.server_ip_address
        try:
            request = requests.get(url, timeout=3)
        except BaseException:
            self.add_error(
                None,
                _('Não foi possível comunicar com o servidor do Edifício.')
            )
            return False

        if request.status_code != 200:
            self.add_error(
                None,
                _('Não foi possível comunicar com o servidor do Edifício.')
            )
            return False

        return True


class EnableTransductorForm(forms.ModelForm):
    class Meta:
        model = EnergyTransductor
        fields = []

    def is_valid(self):
        valid = super(EnableTransductorForm, self).is_valid()

        if not valid:
            return valid

        if self.instance.active:
            self.add_error(
                None,
                _('O transdutor já está ativo.')
            )
            return False

        if not self.instance.building.active:
            self.add_error(
                None,
                _('O Edifício do transdutor está desativado. Ative-o antes' +
                  ' de tentar ativar este transdutor.')
            )
            return False

        url = 'http://' + self.instance.building.server_ip_address
        try:
            request = requests.get(url, timeout=3)
        except BaseException:
            self.add_error(
                None,
                _('Não foi possível comunicar com o servidor do Edifício.')
            )
            return False

        if request.status_code != 200:
            self.add_error(
                None,
                _('Não foi possível comunicar com o servidor do Edifício.')
            )
            return False

        return True


class DisableTransductorForm(forms.ModelForm):
    class Meta:
        model = EnergyTransductor
        fields = []

    def is_valid(self):
        valid = super(DisableTransductorForm, self).is_valid()

        if not valid:
            return valid

        if not self.instance.active:
            self.add_error(
                None,
                _('O transdutor já está desativado.')
            )
            return False

        if not self.instance.building.active:
            self.add_error(
                None,
                _('O Edifício do transdutor está desativado. Ative-o antes' +
                  ' de tentar desativar este transdutor.')
            )
            return False

        url = 'http://' + self.instance.building.server_ip_address
        try:
            request = requests.get(url, timeout=3)
        except BaseException:
            self.add_error(
                None,
                _('Não foi possível comunicar com o servidor do Edifício.')
            )
            return False

        if request.status_code != 200:
            self.add_error(
                None,
                _('Não foi possível comunicar com o servidor do Edifício.')
            )
            return False

        return True

src/smi_unb/transductor/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from smi_unb.api.synchronization import SyncManager
from smi_unb.buildings.models import Building
from .forms import EnergyForm, EnableTransductorForm, DisableTransductorForm
from .models import EnergyTransductor


@login_required
def info(request, transductor_id):
    transductor = get_object_or_404(EnergyTransductor, pk=transductor_id)

    return render(
        request, 'transductor/info.html',
        {
            'campus': transductor.building.campus,
            'building': transductor.building,
            'transductor': transductor
        }
    )


@login_required
@user_passes_test(
    lambda user: user.has_perm("users.manager_transductors"),
    login_url='/painel_controle/',
    redirect_field_name=None)
def new(request, building_id):
    building = get_object_or_404(Building, pk=building_id)

    if request.POST:
        form = EnergyForm(request.POST, building=building)

        if form.is_valid():
            transductor = form.save()

            transductor.synchronized = SyncManager.sync_transductor(
                transductor, new=True)

            transductor.save()

            return HttpResponseRedirect(
                reverse(
                    'buildings:index',
                    kwargs={'building_id': building_id}
                )
            )
    else:
        form = EnergyForm(building=building)

    return render(
        request,
        'transductor/new.html',
        {'form': form, 'campus': building.campus, 'building': building}
    )


@login_required
@user_passes_test(
    lambda user: user.has_perm("users.manager_transductors"),
    login_url='/painel_controle/',
    redirect_field_name=None)
def edit(request, transductor_id):
    transductor = get_object_or_404(EnergyTransductor, pk=transductor_id)

    if request.POST:
        form = EnergyForm(
            request.POST,
            instance=transductor,
            building=transductor.building
        )

        if form.has_changed():
            if form.is_valid():
                transductor = form.save(commit=False)

                transductor.synchronized = SyncManager.sync_transductor(
                    transductor)

                transductor.save()

                return HttpResponseRedirect(
                    reverse(
                        'transductor:info',
                        kwargs={'transductor_id': transductor.id}
                    )
                )
        else:
            form.add_error(None, "Nenhuma Mudança Encontrada.")
    else:
        form = EnergyForm(
            instance=transductor,
            building=transductor.building
        )

    return render(
        request,
        'transductor/edit.html',
        {
            'form': form,
            'building': transductor.building,
            'campus': transductor.building.campus
        }
    )


@login_required
@user_passes_test(
    lambda user: user.has_perm("users.manager_transductors"),
    login_url='/painel_controle/',
    redirect_field_name=None)
def enable(request, transductor_id):
    transductor = get_object_or_404(EnergyTransductor, pk=transductor_id)

    if request.POST:
        form = EnableTransductorForm(request.POST, instance=transductor)

        if form.is_valid():
            transductor = form.save(commit=False)
            transductor.set_transductor_active()
            transductor.synchronized = SyncManager.sync_transductor(
                transductor)
            transductor.save()

            next_page = request.POST.get('next')

            if next_page:
                return HttpResponseRedirect(next_page)

    return HttpResponseRedirect(
        reverse(
            'transductor:info',
            kwargs={'transductor_id': transductor.id}
        )
    )


@login_required
@user_passes_test(
    lambda user: user.has_perm("users.manager_transductors"),
    login_url='/painel_controle/',
    redirect_field_name=None)
def disable(request, transductor_id):
    transductor = get_object_or_404(EnergyTransductor, pk=transductor_id)

    if request.POST:
        form = DisableTransductorForm(request.POST, instance=transductor)

        if form.is_valid():
            transductor = form.save(commit=False)
            transductor.set_transductor_inactive()
            transductor.synchronized = SyncManager.sync_transductor(
                transductor)
            transductor.save()

    return HttpResponseRedirect(
        reverse(
            'transductor:info',
            kwargs={'transductor_id': transductor.id}
        )
    )

src/smi_unb/transductor/templates/transductor/edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
  {{form.instance.name}} - {% trans "Editar Informações" %}
{% endblock %}

{% block extrastyle %}
  <script type="text/javascript" src="{% static 'transductor/js/transductor.js' %}"></script>

  <script type="text/javascript">
    $(document).ready(function() {
      $(window).load(function(){
        load_datetime_picker();
      });
    });
  </script>
{% endblock %}

{% block header %}
<div id="head" class="secondary" style=></div>
{% endblock %}

{% block body %}
<div class="container">

  <ol class="breadcrumb">
    <li><a href="{% url 'index' %}">{% trans "Início" %}</a></li>
    <li><a href="{% url 'dashboard' %}">{% trans "Painel de Controle" %}</a></li>
    <li><a href="{% url 'campuses:index' %}">{% trans "Câmpus" %}</a></li>
    <li><a href="{% url 'campuses:campus_index' campus.url_param %}">{{campus.acronym}}</a></li>
    <li><a href="{% url 'buildings:index' building.id %}">{{building.name}}</a></li>
    <li><a href="{% url 'transductor:info' form.instance.id %}">{{form.instance.name}}</a></li>
    <li class="active">{% trans "Editar Informações" %}</li>
  </ol>

  <div class="row">
    <article class="col-xs-12 maincontent">
      <header class="page-header">
        <h1 class="page-title">{{form.instance.name}} - {% trans "Edição de Informações" %}</h1>
      </header>

      <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-default">
          <div class="panel-body">
            <h3 class="thin text-center">{% trans "Preencha os Campos Corretamente para Editar o Transdutor" %}</h3>
            <hr>

            {% if form.non_field_errors %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  <strong>{{ error|escape }}</strong>
                </div>
              {% endfor %}
            {% endif %}

            <form method="post">
              {% csrf_token %}

              <div class="top-margin">
                <label>{{ form.building.label }}</label>
                {{form.building}}
                <div class="alert-danger">
                  <strong>{{ form.building.errors }}</strong>
                </div>
              </div>

              <div class="top-margin">
                <label>{{ form.model.label }}</label>
                {{form.model}}
                <div class="alert-danger">
                  <strong>{{ form.model.errors }}</strong>
                </div>
              </div>

              <div class="top-margin">
                <label>{{ form.ip_address.label }} <span class="text-danger">*</span></label>
                {{form.ip_address}}
                <div class="alert-danger">
                  <strong>{{ form.ip_address.errors }}</strong>
                </div>
              </div>

              <div class="top-margin">
                <label>{{ form.name.label }} <span class="text-danger">*</span></label>
                {{form.name}}
                <div class="alert-danger">
                  <strong>{{ form.name.errors }}</strong>
                </div>
              </div>

              <div class="top-margin">
                <label>{{ form.serie_number.label }}</label>
                {{form.serie_number}}
                <div class="alert-danger">
                  <strong>{{ form.serie_number.errors }}</strong>
                </div>
              </div>

              <div class="top-margin">
                <label>{{ form.local_description.label }}</label>
                {{form.local_description}}
                <div class="alert-danger">
                  <strong>{{ form.local_description.errors }}</strong>
                </div>
              </div>

              <div class="top-margin">
                <label>{{ form.comments.label }}</label>
                {{form.comments}}
                <div class="alert-danger">
                  <strong>{{ form.comments.errors }}</strong>
                </div>
              </div>

              <div class="top-margin">
                <label>{{ form.calibration_date.label }}</label>

                <div class="input-group date" id="datetimepicker1">
                  {{form.calibration_date}}
                  <span class="input-group-addon">
                      <span class="glyphicon glyphicon-calendar"></span>
                  </span>
                </div>

                <div class="alert-danger">
                  <strong>{{ form.calibration_date.errors }}</strong>
                </div>
              </div>
              <hr>

              <div class="row">
                <div class="col-lg text-center">
                  <button class="btn btn-warning" type="submit" onclick="return confirm('Deseja realmente editar o transdutor?')">{% trans "Salvar Mudanças" %}</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </article>
  </div>
</div>
{% endblock %}

src/smi_unb/transductor/templates/transductor/info.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
  {{transductor.name}} - {% trans "Informações" %}
{% endblock %}

{% block header %}
<div id="head" class="secondary" style=></div>
{% endblock %}

{% block body %}
<div class="container">

  <ol class="breadcrumb">
    <li><a href="{% url 'index' %}">{% trans "Início" %}</a></li>
    <li><a href="{% url 'dashboard' %}">{% trans "Painel de Controle" %}</a></li>
    <li><a href="{% url 'campuses:index' %}">{% trans "Câmpus" %}</a></li>
    <li><a href="{% url 'campuses:campus_index' campus.url_param %}">{{campus.acronym}}</a></li>
    <li><a href="{% url 'buildings:index' building.id %}">{{building.name}}</a></li>
    <li class="active">{{transductor.name}}</li>
  </ol>

  <div class="row">
    <article class="col-xs-12 maincontent">

      <header class="page-header">
        <h1 class="page-title">{{transductor.name}} - {% trans "Informações" %}</h1>
      </header>

      <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
        {% if perms.users.manager_transductors %}
          <div class="text-center">
            <b><a href="{% url 'transductor:edit' transductor.id %}" class="btn btn-warning">{% trans "Editar Informações" %}</a></b>

            {% if transductor.active %}
              <form class="enable_disable_buttons" action="{% url 'transductor:disable' transductor_id=transductor.id %}" method="post">
                {% csrf_token %}
                <button class="btn btn-danger onclick=" onclick="return confirm('Deseja realmente desabilitar?')">{% trans "Desativar Transdutor" %}</button>
              </form>
            {% else %}
              <form class="enable_disable_buttons" action="{% url 'transductor:enable' transductor_id=transductor.id %}" method="post">
                {% csrf_token %}
                <button class="btn btn-success" onclick="return confirm('Deseja realmente habilitar o transdutor?')">{% trans "Ativar Transdutor" %}</button>
              </form>
            {% endif %}
          </div>
        <hr>
        {% endif %}

        <div class="panel panel-default">
          <div class="panel-body">
            <h3 class="thin text-center">{% trans "Informações" %}</h3>
            <hr>

            <div class="top-margin">
              <label>{% trans "Edifício" %}:</label>
              <p>{{transductor.building}}</p>
            </div>

            <div class="top-margin">
              <label>{% trans "Modelo" %}:</label>
              <p>{{transductor.model}}</p>
            </div>

            {% if perms.users.manager_transductors %}
              <div class="top-margin">
                <label>{% trans "Número de IP" %}:</label>
                <p>{{transductor.ip_address}}</p>
              </div>
            {% endif %}

            <div class="top-margin">
              <label>{% trans "Nome" %}:</label>
              <p>{{transductor.name}}</p>
            </div>

            <div class="top-margin">
              <label>{% trans "Descrição do Local Instalado" %}:</label>
              <p>{{transductor.local_description}}</p>
            </div>

            <div class="top-margin">
              <label>{% trans "Comentários" %}:</label>
              <p>{{transductor.comments}}</p>
            </div>

            <div class="top-margin">
              <label>{% trans "Data Última Calibração" %}:</label>
              {% if transductor.calibration_date %}
                <p>{{transductor.calibration_date}}</p>
              {% else %}
                <p>N/A</p>
              {% endif %}
            </div>

            <div class="top-margin">
              <label>{% trans "Data Última Coleta de Dados" %}:</label>
              {% if transductor.energymeasurements_set.last %}
                <p>{{transductor.energymeasurements_set.last.collection_date}}</p>
              {% else %}
                <p>N/A</p>
              {% endif %}
            </div>
          </div> <!-- end div panel- -->
        </div>
      </div>
    </article>
  </div>
</div>
{% endblock %}

src/smi_unb/transductor/templates/transductor/new.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
  {% trans "Cadastrar Transdutor" %}
{% endblock %}

{% block extrastyle %}
  <script type="text/javascript" src="{% static 'transductor/js/transductor.js' %}"></script>

  <script type="text/javascript">
    $(document).ready(function() {
      $(window).load(function(){
        load_datetime_picker();
      });
    });
  </script>
{% endblock %}

{% block header %}
<div id="head" class="secondary" style=></div>
{% endblock %}

{% block body %}
<div class="container">

  <ol class="breadcrumb">
    <li><a href="{% url 'index' %}">{% trans "Início" %}</a></li>
    <li><a href="{% url 'dashboard' %}">{% trans "Painel de Controle" %}</a></li>
    <li><a href="{% url 'campuses:index' %}">{% trans "Câmpus" %}</a></li>
    <li><a href="{% url 'campuses:campus_index' campus.url_param %}">{{campus.acronym}}</a></li>
    <li><a href="{% url 'buildings:index' building.id %}">{{building.name}}</a></li>
    <li class="active">{% trans "Cadastrar Transdutor" %}</li>
  </ol>

  <div class="row">
    <article class="col-xs-12 maincontent">
      <header class="page-header">
        <h1 class="page-title">{{building.name}} - {% trans "Cadastro de Transdutor" %}</h1>
      </header>

      <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-default">
          <div class="panel-body">
            <h3 class="thin text-center">{% trans "Preencha os Campos Corretamente para Cadastrar um Novo Transdutor" %}</h3>
            <hr>

            {% if form.non_field_errors %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  <strong>{{ error|escape }}</strong>
                </div>
              {% endfor %}
            {% endif %}

            <form method="post">
              {% csrf_token %}

              <div class="top-margin">
                <label>{{ form.building.label }}</label>
                {{form.building}}
                <div class="alert-danger">
                  <strong>{{ form.building.errors }}</strong>
                </div>
              </div>

              <div class="top-margin">
                <label>{{ form.model.label }}</label>
                {{form.model}}
                <div class="alert-danger">
                  <strong>{{ form.model.errors }}</strong>
                </div>
              </div>

              <div class="top-margin">
                <label>{{ form.ip_address.label }} <span class="text-danger">*</span></label>
                {{form.ip_address}}
                <div class="alert-danger">
                  <strong>{{ form.ip_address.errors }}</strong>
                </div>
              </div>

              <div class="top-margin">
                <label>{{ form.name.label }} <span class="text-danger">*</span></label>
                {{form.name}}
                <div class="alert-danger">
                  <strong>{{ form.name.errors }}</strong>
                </div>
              </div>

              <div class="top-margin">
                <label>{{ form.serie_number.label }}</label>
                {{form.serie_number}}
                <div class="alert-danger">
                  <strong>{{ form.serie_number.errors }}</strong>
                </div>
              </div>

              <div class="top-margin">
                <label>{{ form.local_description.label }}</label>
                {{form.local_description}}
                <div class="alert-danger">
                  <strong>{{ form.local_description.errors }}</strong>
                </div>
              </div>

              <div class="top-margin">
                <label>{{ form.comments.label }}</label>
                {{form.comments}}
                <div class="alert-danger">
                  <strong>{{ form.comments.errors }}</strong>
                </div>
              </div>

              <div class="top-margin">
                <label>{{ form.calibration_date.label }}</label>

                <div class="input-group date" id="datetimepicker1">
                  {{form.calibration_date}}
                  <span class="input-group-addon">
                      <span class="glyphicon glyphicon-calendar"></span>
                  </span>
                </div>

                <div class="alert-danger">
                  <strong>{{ form.calibration_date.errors }}</strong>
                </div>
              </div>
              <hr>

              <div class="row">
                <div class="col-lg text-center">
                  <button class="btn btn-success" type="submit" onclick="return confirm('Deseja realmente cadastrar o transdutor?')">{% trans "Cadastrar" %}</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </article>
  </div>
</div>
{% endblock %}