src/smi_unb/buildings/urls.py
from django.conf.urls import url
from . import views

app_name = 'buildings'
urlpatterns = [
    url(
        r'^novo&campus=(?P<campus_string>[\w\-]+)/$',
        views.new_building,
        name="new_building"
    ),
    url(
        r'^(?P<building_id>[0-9]+)/$',
        views.index,
        name="index"
    ),
    url(
        r'^(?P<building_id>[0-9]+)/info/$',
        views.building_info,
        name="building_info"
    ),
    url(
        r'^(?P<building_id>[0-9]+)/transdutores_defeituosos/$',
        views.building_broken_transductors,
        name="building_broken_transductors"
    ),
    url(
        r'^(?P<building_id>[0-9]+)/edit\&campus=(?P<campus_string>[\w\-]+)/$',
        views.edit_building,
        name="edit_building"
    ),
    url(
        r'^(?P<building_id>[0-9]+)/enable/$',
        views.enable_building,
        name="enable_building"
    ),
    url(
        r'^(?P<building_id>[0-9]+)/disable/$',
        views.disable_building,
        name="disable_building"
    ),
    url(
        r'^(?P<building_id>[0-9]+)/transdutores_desativados/$',
        views.inactive_transductors,
        name="inactive_transductors"
    ),
]

src/smi_unb/campuses/urls.py
from django.conf.urls import url

from . import views

app_name = 'campuses'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(
        r'^(?P<campus_string>[\w\-]+)/$',
        views.campus_index,
        name="campus_index"
    ),
    url(
        r'^(?P<campus_string>[\w\-]+)/info/$',
        views.campus_info,
        name="campus_info"
    ),
    url(
        r'^(?P<campus_string>[\w\-]+)/desativados/$',
        views.inactive_buildings,
        name="inactive_buildings"
    ),
]

src/smi_unb/urls.py
import smi_unb.api.views as api_views

from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers

from smi_unb import views

router = routers.DefaultRouter()
router.register(r'building', api_views.BuildingViewSet)
router.register(r'energy_measurement', api_views.EnergyMeasurementsViewSet)
router.register(r'energy_transductor', api_views.EnergyTransductorViewSet)

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^campi/', include('smi_unb.campuses.urls', namespace="campuses")),
    url(r'^painel_controle/$', views.dashboard, name="dashboard"),
    url(r'^reports/', include('smi_unb.report.urls', namespace="report")),
    url(r'^usuarios/', include('smi_unb.users.urls', namespace="users")),
    url(
        r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework')),
    url(
        r'^autenticacao/',
        include('smi_unb.authentication.urls', namespace="authentication")),
    url(
        r'^minha_conta/',
        include('smi_unb.my_account.urls', namespace="my_account")),
    url(
        r'^predios/',
        include('smi_unb.buildings.urls', namespace="buildings")),
    url(
        r'^recuperar_senha/',
        include('smi_unb.retrieve_password.urls', namespace="retrieve")),
    url(
        r'^transdutor/',
        include('smi_unb.transductor.urls', namespace="transductor")),
]

src/smi_unb/campuses/models.py
from django.db import models


class AdministrativeRegion(models.Model):
    name = models.CharField(max_length=50)


class Campus(models.Model):
    administrative_region = models.ForeignKey(AdministrativeRegion,
                                              on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=50)
    acronym = models.CharField(max_length=20)
    address = models.CharField(max_length=150)
    phone = models.CharField(max_length=30)
    url_param = models.CharField(max_length=15, unique=True)
    website_address = models.CharField(max_length=100)
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_all_active_buildings(self):
        return self.building_set.filter(active=True)

    def get_all_inactive_buildings(self):
        return self.building_set.filter(active=False)

src/smi_unb/campuses/views.py
from django.contrib.auth.decorators import user_passes_test, login_required
from django.shortcuts import render, get_object_or_404

from smi_unb.campuses.models import Campus


@login_required
def index(request):
    campuses = Campus.objects.all()

    return render(request, 'campuses/index.html', {'campuses': campuses})


@login_required
def campus_index(request, campus_string):
    campus = get_object_or_404(Campus, url_param=campus_string)

    buildings = campus.get_all_active_buildings()
    inactive_buildings = bool(campus.get_all_inactive_buildings())

    return render(
        request,
        'campuses/campus_index.html',
        {
            'campus': campus,
            'buildings': buildings,
            'inactive_buildings': inactive_buildings
        }
    )


@login_required
def campus_info(request, campus_string):
    campus = get_object_or_404(Campus, url_param=campus_string)

    return render(request, 'campuses/campus_info.html', {'campus': campus})


@login_required
@user_passes_test(
    lambda user: user.has_perm("users.manager_buildings"),
    login_url='/painel_controle/',
    redirect_field_name=None)
def inactive_buildings(request, campus_string):
    campus = get_object_or_404(Campus, url_param=campus_string)

    inactive_buildings = campus.get_all_inactive_buildings()

    return render(
        request,
        'campuses/inactive_buildings.html',
        {
            'campus': campus,
            'inactive_buildings': inactive_buildings
        }
    )

src/smi_unb/campuses/templates/campuses/campus_index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
  {{campus.acronym}}
{% endblock %}

{% block extrastyle %}
  <link rel="stylesheet" type="text/css" href="{% static 'campuses/css/campuses.css' %}" />
{% endblock %}

{% block header %}
<div id="head" class="secondary" style=></div>
{% endblock %}

{% block body %}
<div class="container">

  <ol class="breadcrumb">
    <li><a href="{% url 'index' %}">{% trans "Início" %}</a></li>
    <li><a href="{% url 'dashboard' %}">{% trans "Painel de Controle" %}</a></li>
    <li><a href="{% url 'campuses:index' %}">{% trans "Câmpus" %}</a></li>
    <li class="active">{{campus.acronym}}</li>
  </ol>

  <div class="row">
    <article class="col-xs-12 maincontent">

      <header class="page-header">
        <h1 class="page-title">{{campus.name}}</h1>
      </header>

      <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
        <div class="text-center">
          <b><a href="{% url 'campuses:campus_info' campus.url_param %}" class="btn btn-primary">{% trans "Informações do Campus" %}</a></b>

          {% if perms.users.manager_buildings %}
            <b><a href="{% url 'buildings:new_building' campus.url_param%}" class="btn btn-success">{% trans "Cadastrar Edifício" %}</a></b>

            {% if inactive_buildings %}
              <b><a href="{% url 'campuses:inactive_buildings' campus.url_param%}" class="btn btn-info">{% trans "Edifícios Desativados" %}</a></b>
            {% endif %}
          {% endif %}
        </div>
        <hr>

        <div class="panel panel-default">
          <div class="panel-body">
            <h3 class="thin text-center">{% trans "Lista de Edifícios" %}</h3>
            <hr>
            {% if buildings %}
              <table id="centered_table" class="table table-bordered">
                <thead>
                  <tr>
                    <th>{% trans "Nome" %}</th>
                    <th>{% trans "Transdutores Funcionando" %}</th>
                    <th>{% trans "Transdutores Defeituosos" %}</th>
                  </tr>
                </thead>

                <tbody>
                  {% for building in buildings %}
                    <tr>
                      <td><a href="{% url 'buildings:index' building.id %}">{{building.name}}</a></td>

                      <td>{{building.get_all_working_transductors.count}}</td>

                      {% if building.get_all_broken_transductors %}
                        <td><a id="a_broken_transductor" href="{% url 'buildings:building_broken_transductors' building.id %}">{{building.get_all_broken_transductors.count}}</a></td>
                        </td>
                      {% else %}
                      <td>0</td>
                      {% endif %}
                    </tr>
                  {% endfor %}
                </tbody>
              </table>

            {% else %}
              <div class="container">
                <div class="starter-template">
                  <h2>{% trans "Nenhum Edifício Registrado" %}</h2>
                </div>
              </div>
            {% endif %}
          </div> <!-- end div panel- -->
        </div>
      </div>
    </article>
  </div>
</div>
{% endblock %}

src/smi_unb/campuses/templates/campuses/campus_info.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
  {{campus.acronym}} - {% trans "Informações" %}
{% endblock %}

{% block header %}
<div id="head" class="secondary" style=></div>
{% endblock %}

{% block body %}
<div class="container">

  <ol class="breadcrumb">
    <li><a href="{% url 'index' %}">{% trans "Início" %}</a></li>
    <li><a href="{% url 'dashboard' %}">{% trans "Painel de Controle" %}</a></li>
    <li><a href="{% url 'campuses:index' %}">{% trans "Câmpus" %}</a></li>
    <li><a href="{% url 'campuses:campus_index' campus.url_param %}">{{campus.acronym}}</a></li>
    <li class="active">{% trans "Informações do Campus" %}</li>
  </ol>

  <div class="row">
    <article class="col-xs-12 maincontent">

      <header class="page-header">
        <h1 class="page-title">{{campus.name}}</h1>
      </header>

      <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">

        <div class="panel panel-default">
          <div class="panel-body">
            <h3 class="thin text-center">{% trans "Informações" %}</h3>
            <hr>

            <div class="top-margin">
              <label>{% trans "Região Administrativa" %}:</label>
              <p>{{campus.administrative_region.name}}</p>
            </div>

            <div class="top-margin">
              <label>{% trans "Nome" %}:</label>
              <p>{{campus.name}}</p>
            </div>

            <div class="top-margin">
              <label>{% trans "Sigla" %}:</label>
              <p>{{campus.acronym}}</p>
            </div>

            <div class="top-margin">
              <label>{% trans "Endereço" %}:</label>
              <p>{{campus.address}}</p>
            </div>

            <div class="top-margin">
              <label>{% trans "Telefone" %}:</label>
              <p>{{campus.phone}}</p>
            </div>
          </div> <!-- end div panel- -->
        </div>
      </div>
    </article>
  </div>
</div>
{% endblock %}

src/smi_unb/campuses/templates/campuses/inactive_buildings.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
  {{campus.acronym}} - {% trans "Edifícios Desativados" %}
{% endblock %}

{% block extrastyle %}
  <link rel="stylesheet" type="text/css" href="{% static 'campuses/css/campuses.css' %}" />
{% endblock %}

{% block header %}
<div id="head" class="secondary" style=></div>
{% endblock %}

{% block body %}
<div class="container">

  <ol class="breadcrumb">
    <li><a href="{% url 'index' %}">{% trans "Início" %}</a></li>
    <li><a href="{% url 'dashboard' %}">{% trans "Painel de Controle" %}</a></li>
    <li><a href="{% url 'campuses:index' %}">{% trans "Câmpus" %}</a></li>
    <li><a href="{% url 'campuses:campus_index' campus.url_param %}">{{campus.acronym}}</a></li>
    <li class="active">{% trans "Edifícios Desativados" %}</li>
  </ol>

  <div class="row">
    <article class="col-xs-12 maincontent">

      <header class="page-header">
        <h1 class="page-title">{{campus.name}} - {% trans "Edifícios Desativados" %}</h1>
      </header>

      <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
        <div class="panel panel-default">
          <div class="panel-body">
            <h3 class="thin text-center">{% trans "Lista de Edifícios" %}</h3>
            <hr>

            {% if inactive_buildings %}
              <table id="centered_table" class="table table-bordered">
                <thead>
                  <tr>
                    <th>{% trans "Nome" %}</th>
                    <th>{% trans "Transdutores Funcionando" %}</th>
                    <th>{% trans "Transdutores Defeituosos" %}</th>
                    <th>{% trans "Opções" %}</th>
                  </tr>
                </thead>

                <tbody>
                  {% for building in inactive_buildings %}
                    <tr>
                      <td><a href="{% url 'buildings:index' building.id %}">{{building.name}}</a></td>

                      <td>{{building.transductor_set.count}}</td>

                      {% if building.get_all_broken_transductors %}
                        <td><a id="a_broken_transductor" href="{% url 'buildings:building_broken_transductors' building.id %}">{{building.get_all_broken_transductors.count}}</a></td>
                        </td>
                      {% else %}
                      <td>0</td>
                      {% endif %}

                      <td>
                        <form class="enable_disable_buttons" action="{% url 'buildings:enable_building' building.id %}" method="post">
                          {% csrf_token %}
                          <button class="btn btn-success" onclick="return confirm('Deseja realmente habilitar o edifício?')">{% trans "Ativar Edifício" %}</button>
                          <input type="hidden" name="next" value="{% url 'campuses:campus_index' campus.url_param %}">
                        </form>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>

            {% else %}
              <div class="container">
                <div class="starter-template">
                  <h2>{% trans "Nenhum Edifício Desativado" %}</h2>
                </div>
              </div>
            {% endif %}
          </div> <!-- end div panel- -->
        </div>
      </div>
    </article>
  </div>
</div>
{% endblock %}

src/smi_unb/campuses/templates/campuses/index.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}
  {% trans "Câmpus da UnB" %}
{% endblock %}

{% block header %}
<div id="head" class="secondary" style=></div>
{% endblock %}

{% block body %}
<div class="container">

  <ol class="breadcrumb">
    <li><a href="{% url 'index' %}">{% trans "Início" %}</a></li>
    <li><a href="{% url 'dashboard' %}">{% trans "Painel de Controle" %}</a></li>
    <li class="active">{% trans "Câmpus" %}</li>
  </ol>

  <div class="row">
    <article class="col-xs-12 maincontent">
      <header class="page-header">
        <h1 class="page-title">{% trans "Câmpus da Universidade" %}</h1>
      </header>

      <div class="container">
        <h2 class="text-center thin">{% trans "Escolha um Campus" %}</h2>

        <div class="row">
          {% for campus in campuses %}
            <div class="col-lg-3 col-md-6 text-center">
              <div class="service-box">
                <i class="fa fa-4x fa-university sr-icons"></a></i>
                <h3><a href="{% url 'campuses:campus_index' campus.url_param%}">{{campus.acronym}}</a></h3>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
      <hr>
    </article>
  </div>
</div>
{% endblock %}