src/smi_unb/authentication/urls.py
from django.conf.urls import url

from . import views

app_name = 'authentication'

urlpatterns = [
    url(r'^$', views.make_login, name='make_login'),
    url(r'^logout/$', views.make_logout, name='make_logout'),
]

src/smi_unb/campuses/urls.py
from django.conf.urls import url

from . import views

app_name = 'campuses'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(
        r'^(?P<campus_string>[\w\-]+)/$',
        views.campus_index,
        name="campus_index"
    ),
    url(
        r'^(?P<campus_string>[\w\-]+)/info/$',
        views.campus_info,
        name="campus_info"
    ),
    url(
        r'^(?P<campus_string>[\w\-]+)/desativados/$',
        views.inactive_buildings,
        name="inactive_buildings"
    ),
]

src/smi_unb/report/urls.py
from django.conf.urls import url

from . import views

app_name = 'report'

urlpatterns = [
    url(r'^generate_graph/$', views.generate_graph, name="generate_graph"),
]

src/smi_unb/urls.py
import smi_unb.api.views as api_views

from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers

from smi_unb import views

router = routers.DefaultRouter()
router.register(r'building', api_views.BuildingViewSet)
router.register(r'energy_measurement', api_views.EnergyMeasurementsViewSet)
router.register(r'energy_transductor', api_views.EnergyTransductorViewSet)

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^campi/', include('smi_unb.campuses.urls', namespace="campuses")),
    url(r'^painel_controle/$', views.dashboard, name="dashboard"),
    url(r'^reports/', include('smi_unb.report.urls', namespace="report")),
    url(r'^usuarios/', include('smi_unb.users.urls', namespace="users")),
    url(
        r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework')),
    url(
        r'^autenticacao/',
        include('smi_unb.authentication.urls', namespace="authentication")),
    url(
        r'^minha_conta/',
        include('smi_unb.my_account.urls', namespace="my_account")),
    url(
        r'^predios/',
        include('smi_unb.buildings.urls', namespace="buildings")),
    url(
        r'^recuperar_senha/',
        include('smi_unb.retrieve_password.urls', namespace="retrieve")),
    url(
        r'^transdutor/',
        include('smi_unb.transductor.urls', namespace="transductor")),
]

src/smi_unb/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^novo/$', views.new_user, name="new_user"),
    url(r'^(?P<user_id>[0-9]+)/$', views.info_user, name="info_user"),
    url(r'^(?P<user_id>[0-9]+)/editar/$',
        views.edit_user,
        name="edit_user"),
    url(r'^(?P<user_id>[0-9]+)/delete/$',
        views.delete_user,
        name="delete_user"),
    url(r'^logging_list/$', views.logging_list, name="logging_list"),
]

src/smi_unb/authentication/forms.py
from django import forms
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'password', ]

    email = forms.CharField(
        label="E-mail",
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'name': 'email',
                'size': 30,
                'type': 'text'
            }
        )
    )

    password = forms.CharField(
        label="Senha",
        max_length=16,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'name': 'password',
                'size': 16,
                'type': 'password'
            }
        )
    )

    def is_valid(self):
        valid = super(LoginForm, self).is_valid()

        if not valid:
            return False

        try:
            user = User.objects.get(email=self.cleaned_data['email'])
        except User.DoesNotExist:
            self.add_error(None, 'Email ou Senha Inválidos.')
            return False

        if not check_password(self.cleaned_data['password'], user.password):
            self.add_error(None, 'Email ou Senha Inválidos.')
            return False

        return True

src/smi_unb/api/views.py
from django.shortcuts import get_object_or_404
from django.utils.datastructures import MultiValueDictKeyError
from rest_framework import viewsets
from rest_framework.response import Response

from smi_unb.buildings.models import Building
from smi_unb.transductor.models import EnergyTransductor, EnergyMeasurements
from .serializers import BuildingSerializer, EnergyTransductorSerializer, \
                         EnergyMeasurementsSerializer


class BuildingViewSet(viewsets.ModelViewSet):
    queryset = Building.objects.all()
    serializer_class = BuildingSerializer


class EnergyTransductorViewSet(viewsets.ModelViewSet):
    queryset = EnergyTransductor.objects.all()
    serializer_class = EnergyTransductorSerializer

    def create(self, request, *args, **kwargs):
        try:
            update_collection = self.request.query_params['update_collection']
        except MultiValueDictKeyError:
            return super(EnergyTransductorViewSet, self).create(
                request, *args, **kwargs)
        else:
            if update_collection == 'true':
                for transductor_data in request.data:
                    instance = get_object_or_404(
                        EnergyTransductor, id=transductor_data['id'])

                    energy_serializer = self.get_serializer(
                        instance=instance, data=transductor_data, partial=True)

                    energy_serializer.is_valid(raise_exception=True)
                    self.perform_update(energy_serializer)

            serializer = self.get_serializer(self.queryset, many=True)
            return Response(serializer.data)


class EnergyMeasurementsViewSet(viewsets.ModelViewSet):
    queryset = EnergyMeasurements.objects.all()
    serializer_class = EnergyMeasurementsSerializer

    def get_queryset(self):
        try:
            last_measurements = self.request.query_params['last']
        except MultiValueDictKeyError:
            self.queryset = EnergyMeasurements.objects.all()
        else:
            if last_measurements == 'true':
                self.queryset = []

                transductors = EnergyTransductor.objects.filter(active=True)

                for transductor in transductors:
                    measurements = transductor.get_last_measurements_or_all()
                    self.queryset += measurements
            else:
                self.queryset = EnergyMeasurements.objects.all()

        return self.queryset

src/smi_unb/authentication/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render

from .forms import LoginForm


def make_login(request):
    teste = request
    next_page = request.POST.get('next', request.GET.get('next', ''))

    if request.user.is_authenticated:
        if next_page:
            return HttpResponseRedirect(next_page)
        else:
            return HttpResponseRedirect(reverse('dashboard'))
    else:
        if request.POST:
            form = LoginForm(request.POST)

            if form.is_valid():
                email = form.cleaned_data['email']
                password = form.cleaned_data['password']

                user = authenticate(username=email, password=password)

                if user is not None and user.is_active:
                    login(teste, user)

                    if next_page:
                        return HttpResponseRedirect(next_page)
                    else:
                        return HttpResponseRedirect(reverse('dashboard'))
        else:
            form = LoginForm()

    return render(request, "users/login.html", {'form': form})


@login_required
def make_logout(request, *args, **kwargs):
    kwargs['next_page'] = reverse('index')

    return logout(request, *args, **kwargs)

src/smi_unb/buildings/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.utils.translation import ugettext as _

from smi_unb.api.synchronization import SyncManager
from smi_unb.campuses.models import Campus
from .forms import BuildingForm, EnableBuildingForm, DisableBuildingForm
from .models import Building


@login_required
def index(request, building_id):
    building = get_object_or_404(Building, pk=building_id)

    transductors_list = building.get_all_active_transductors()
    inactive_transductors = bool(building.get_all_inactive_transductors())

    return render(
        request,
        'buildings/building_index.html',
        {
            'campus': building.campus,
            'building': building,
            'transductors_list': transductors_list,
            'inactive_transductors': inactive_transductors
        }
    )


@login_required
@user_passes_test(
    lambda user: user.has_perm("users.manager_buildings"),
    login_url='/painel_controle/',
    redirect_field_name=None)
def new_building(request, campus_string):
    campus = get_object_or_404(Campus, url_param=campus_string)

    if request.POST:
        form = BuildingForm(request.POST, campus=campus)

        if form.is_valid():
            building = form.save()

            building.synchronized = SyncManager.sync_building(
                building, new=True)

            building.save()

            return HttpResponseRedirect(
                reverse(
                    'campuses:campus_index',
                    kwargs={'campus_string': campus.url_param}
                )
            )
    else:
        form = BuildingForm(
            campus=campus
        )

    return render(
        request,
        'buildings/new_building.html',
        {'campus': campus, 'form': form}
    )


@login_required
@user_passes_test(
    lambda user: user.has_perm("users.manager_buildings"),
    login_url='/painel_controle/',
    redirect_field_name=None)
def edit_building(request, building_id, campus_string):
    building = get_object_or_404(Building, pk=building_id)

    if not building.campus.url_param == campus_string:
        return render(request, '404.html')

    if request.POST:
        form = BuildingForm(
            request.POST,
            instance=building,
            campus=building.campus
        )

        if form.is_valid():
            if form.has_changed():
                building = form.save(commit=False)

                building.synchronized = SyncManager.sync_building(
                    building)

                building.save()

                return HttpResponseRedirect(
                    reverse(
                        'buildings:building_info',
                        kwargs={
                            'building_id': building.id
                        }
                    )
                )
            else:
                form.add_error(None, _("Nenhuma Mudança Encontrada."))
    else:
        form = BuildingForm(instance=building, campus=building.campus)

    return render(
        request,
        'buildings/edit_building.html',
        {'campus': building.campus, 'building': building, 'form': form}
    )


@login_required
@user_passes_test(
    lambda user: user.has_perm("users.manager_buildings"),
    login_url='/painel_controle/',
    redirect_field_name=None)
def enable_building(request, building_id):
    building = get_object_or_404(Building, pk=building_id)

    if request.POST:
        form = EnableBuildingForm(request.POST, instance=building)

        if form.is_valid():
            building = form.save(commit=False)
            building.set_building_active()
            building.synchronized = SyncManager.sync_building(
                building)
            building.save()

            next_page = request.POST.get('next')

            if next_page:
                return HttpResponseRedirect(next_page)

    return HttpResponseRedirect(
        reverse(
            'buildings:building_info',
            kwargs={'building_id': building.id}
        )
    )


@login_required
@user_passes_test(
    lambda user: user.has_perm("users.manager_buildings"),
    login_url='/painel_controle/',
    redirect_field_name=None)
def disable_building(request, building_id):
    building = get_object_or_404(Building, pk=building_id)

    if request.POST:
        form = DisableBuildingForm(request.POST, instance=building)

        if form.is_valid():
            building = form.save(commit=False)
            building.set_building_inactive()
            building.synchronized = SyncManager.sync_building(
                building)
            building.save()

    return HttpResponseRedirect(
        reverse(
            'buildings:building_info',
            kwargs={'building_id': building.id}
        )
    )


@login_required
def building_info(request, building_id):
    building = get_object_or_404(Building, pk=building_id)

    return render(
        request,
        'buildings/building_info.html',
        {
            'campus': building.campus,
            'building': building
        }
    )


@login_required
def building_broken_transductors(request, building_id):
    building = get_object_or_404(Building, pk=building_id)

    broken_transductors = building.get_all_broken_transductors()

    return render(
        request,
        'buildings/building_broken_transductors.html',
        {
            'campus': building.campus,
            'building': building,
            'broken_transductors': broken_transductors
        }
    )


@login_required
@user_passes_test(
    lambda user: user.has_perm("users.manager_transductors"),
    login_url='/painel_controle/',
    redirect_field_name=None)
def inactive_transductors(request, building_id):
    building = get_object_or_404(Building, pk=building_id)
    inactive_transductors = building.get_all_inactive_transductors()

    return render(
        request,
        'buildings/inactive_transductors.html',
        {
            'campus': building.campus,
            'building': building,
            'inactive_transductors': inactive_transductors
        }
    )

src/smi_unb/campuses/views.py
from django.contrib.auth.decorators import user_passes_test, login_required
from django.shortcuts import render, get_object_or_404

from smi_unb.campuses.models import Campus


@login_required
def index(request):
    campuses = Campus.objects.all()

    return render(request, 'campuses/index.html', {'campuses': campuses})


@login_required
def campus_index(request, campus_string):
    campus = get_object_or_404(Campus, url_param=campus_string)

    buildings = campus.get_all_active_buildings()
    inactive_buildings = bool(campus.get_all_inactive_buildings())

    return render(
        request,
        'campuses/campus_index.html',
        {
            'campus': campus,
            'buildings': buildings,
            'inactive_buildings': inactive_buildings
        }
    )


@login_required
def campus_info(request, campus_string):
    campus = get_object_or_404(Campus, url_param=campus_string)

    return render(request, 'campuses/campus_info.html', {'campus': campus})


@login_required
@user_passes_test(
    lambda user: user.has_perm("users.manager_buildings"),
    login_url='/painel_controle/',
    redirect_field_name=None)
def inactive_buildings(request, campus_string):
    campus = get_object_or_404(Campus, url_param=campus_string)

    inactive_buildings = campus.get_all_inactive_buildings()

    return render(
        request,
        'campuses/inactive_buildings.html',
        {
            'campus': campus,
            'inactive_buildings': inactive_buildings
        }
    )

src/smi_unb/my_account/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from .forms import ChangePasswordForm, SelfEditForm


@login_required
def index(request):
    return render(request, 'my_account/index.html')


@login_required
def self_edit(request):
    user = get_object_or_404(User, pk=request.user.id)

    if request.POST:
        form = SelfEditForm(request.POST, instance=user)

        if form.is_valid():
            if form.has_changed():
                form.save()

                messages.success(
                    request,
                    'Suas informações foram alteradas com sucesso!'
                )

                return HttpResponseRedirect(reverse('my_account:index'))
            else:
                form.add_error(None, "Nenhuma Mudança Encontrada.")
    else:
        form = SelfEditForm(instance=user)

    return render(request, 'my_account/self_edit.html', {'form': form})


@login_required
def change_password(request):
    if request.POST:
        form = ChangePasswordForm(request.user, request.POST)

        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Sua senha foi alterada com sucesso!')

            return HttpResponseRedirect(reverse('my_account:index'))
    else:
        form = ChangePasswordForm(request.user)

    return render(request, 'my_account/change_password.html', {'form': form})

src/smi_unb/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load staticfiles %}
{% load i18n %}

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="SHORTCUT ICON" href="{% static 'images/logo_icon.png' %}">

  <title>SMI-UnB | {% block title %}{% endblock %}</title>

  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  <!-- Loaging css -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/open-sans.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}">

  <!-- Custom css -->
  <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">

  <!-- Loaging jQuery -->
  <script type="text/javascript" src="{% static 'js/moment-with-locales.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap-select.min.js' %}"></script>
  {% block extrastyle %}{% endblock %}
</head>

<body class="home">
  <div class="navbar navbar-default navbar-fixed-top" >
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
        </button>
        <a class="navbar-brand page-scroll" href="{% url 'index' %}">SMI - UnB</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a class="page-scroll" href="{% url 'index' %}">{% trans "Início" %}</a></li>
          {% if user.is_authenticated %}
          <li><a class="page-scroll" href="{% url 'dashboard' %}">{% trans "Painel de Controle" %}</a></li>
          <li><a class="page-scroll" href="{% url 'my_account:index' %}">{% trans "Minha Conta" %}</a></li>
          <li><a class="btn" href="{% url 'authentication:make_logout'%}">{% trans "Sair" %}</a></li>
        {% else %}
          <li><a class="btn" href="{% url 'authentication:make_login'%}">{% trans "Login" %}</a></li>
        {% endif %}
        </ul>
      </div>
    </div>
  </div>

{% block header %}
{% endblock %}

<body>
{% block body %}
{% endblock %}
</body>

</html>

src/smi_unb/templates/dashboard.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}
  {% trans "Painel de Controle" %}
{% endblock %}

{% block header %}
<div id="head" class="secondary" style=></div>
{% endblock %}

{% block body %}
<div class="container">

  <ol class="breadcrumb">
    <li><a href="{% url 'index' %}">{% trans "Início" %}</a></li>
    <li class="active">{% trans "Painel de Controle" %}</li>
  </ol>

  <div class="row">
    <article class="col-xs-12 maincontent">
      <header class="page-header">
        <h1 class="page-title">{% trans "Painel de Controle" %}</h1>
      </header>

      <div class="container">
        <h2 class="text-center thin">{% trans "Escolha uma opção" %}</h2>

        <div class="row">
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box">
              <i class="fa fa-4x fa-university sr-icons"></a></i>
              <h3><a href="{% url 'campuses:index' %}">{% trans "Câmpus da Universidade" %}</a></h3>
              <p>{% trans "Todos os câmpus com seus respectivos edifícios e transdutores" %}</p>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box">
              <i class="fa fa-4x fa-line-chart sr-icons"></i>
              <h3><a href="{% url 'report:generate_graph' %}">{% trans "Gráficos" %}</a></h3>
              <p>{% trans "Gráficos para os aparelhos de medição" %}</p>
            </div>
          </div>

          {% if user.is_superuser %}
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box">
              <i class="fa fa-4x fa-users sr-icons"></i>
              <h3><a href="{% url 'users:index' %}">{% trans "Usuários" %}</a></h3>
              <p>{% trans "Gerência de usuários e controle de permissões" %}</p>
            </div>
          </div>
          {% endif %}

          {% if perms.users.see_logging %}
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box">
              <i class="fa fa-4x fa-history sr-icons"></i>
              <h3><a href="{% url 'users:logging_list' %}">{% trans "Log do Sistema" %}</a></h3>
              <p>{% trans "Registro de informações importantes na aplicação" %}</p>
            </div>
          </div>
          {% endif %}

        </div>
      </div>
      <hr>
    </article>
  </div>
</div>
{% endblock %}

src/smi_unb/templates/index.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
  {% trans "Home" %}
{% endblock %}

{% block header %}
<header class="main-header">
  <div class="header-content">
    <div class="header-content-inner">
      <h1 id="homeHeading">Sistema de Monitoramento de Insumos - Universidade de Brasília</h1>
      <hr>
      {% if user.is_authenticated %}
        <p>Olá {{user.first_name}}, para onde deseja ir?</p>
        <a href="{% url 'dashboard' %}" class="btn btn-primary btn-xl page-scroll">Painel de Controle</a>
        <a href="{% url 'my_account:index' %}" class="btn btn-warning btn-xl page-scroll">Minha Conta</a>
      {% else %}
        <p>Bem-vindo ao SMI - UnB, a plataforma web para monitoramento temporal de recursos importantes para a Universidade. Realize o login para ter maior acesso ao sistema!</p>
        <a href="{% url 'authentication:make_login' %}" class="btn btn-primary btn-xl page-scroll">Login</a>
      {% endif %}
    </div>
  </div>
</header>
{% endblock %}

{% block body %}
{% endblock %}

src/smi_unb/templates/languages.html
{% load i18n %}

{% get_available_languages as LANGUAGES %}

<div class="idiomas" style = "    margin-top: 8px; margin-left: 8px;">
  <form action="/i18n/setlang/" method="post">{% csrf_token %}
    <select class = "form-control" name="language" onchange="submit()">
      <option> {% trans "Change Language" %}</option>
        {% for lang in LANGUAGES %}
      <option value="{{ lang.0 }}">{{ lang.1 }}</option>
      {% endfor %}
    </select>
  </form>
</div>

src/smi_unb/templates/notification.html
<div class="custom-alert" id="allert-container">

</div>